### ISSUE TITLE
The graphics_view example can not work.

### ISSUE THREAD

**Issue by Thatfreesky** [frmdstryr/enamlx#12]
```
Last login: Tue Oct 30 09:43:03 on ttys006
iridium-MacBook-Pro:~ iridium$ source activate enamlx
(enamlx) iridium-MacBook-Pro:~ iridium$ conda list
# packages in environment at /Users/iridium/anaconda3/envs/enamlx:
#
# Name                    Version                   Build  Channel
atom                      0.4.1            py36h2d50403_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
enaml                     0.10.2           py36h2d50403_1    conda-forge
enamlx                    0.3.0                     <pip>
future                    0.17.0                py36_1000    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libpng                    1.6.35               ha92aebf_2    conda-forge
ncurses                   6.1                  h0a44026_0  
numpy                     1.15.3                    <pip>
openssl                   1.0.2p               h470a237_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
ply                       3.11                       py_1    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
pyqtgraph                 0.10.0                    <pip>
python                    3.6.6                h5001a0f_0    conda-forge
python.app                1.2                    py36_200    conda-forge
qt                        5.6.2                hd4c90f3_9    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
readline                  7.0                  h1de35cc_5  
setuptools                40.5.0                   py36_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
sqlite                    3.25.2               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
wheel                     0.32.2                   py36_0    conda-forge
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               hf3cbc9b_2  
(enamlx) iridium-MacBook-Pro:~ iridium$ enaml-run /Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_interact.enaml
Traceback (most recent call last):
  File "/Users/iridium/anaconda3/envs/enamlx/bin/enaml-run", line 11, in <module>
    sys.exit(main())
  File "/Users/iridium/anaconda3/envs/enamlx/lib/python3.6/site-packages/enaml/runner.py", line 62, in main
    exec_(code, ns)
  File "/Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_interact.enaml", line 9, in 
    )
ImportError: cannot import name 'GraphicsView'
(enamlx) iridium-MacBook-Pro:~ iridium$ 

```

**Comment by frmdstryr** [comment]
Did you install enamlx from `pip install git+https://github.com/frmdstryr/enamlx`? The `GraphicsView` widget was not in version 0.3

**Comment by Thatfreesky** [comment]
Thanks for you help.
No, I install exnaml directly by `pip install enamlx`. I follow your command and reinstall enamlx from `pip install git+https://github.com/frmdstryr/enamlx`. The graphics_interact.enaml example can show a window:
<img width="248" alt="screen shot 2018-10-30 at 9 58 52 am" src="https://user-images.githubusercontent.com/15063337/47690872-c7957c80-dc2a-11e8-9c9c-2dbd352041b0.png">
But it looks strange.

On the other hand, the graphics_items example still can not work.
```
Last login: Tue Oct 30 09:57:07 on ttys007
iridium-MacBook-Pro:~ iridium$ source activate enamlx
(enamlx) iridium-MacBook-Pro:~ iridium$ enaml-run /Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_interact.enaml
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
QMacCGContext:: Unsupported painter devtype type 1
(enamlx) iridium-MacBook-Pro:~ iridium$ enaml-run /Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_items.enaml
Traceback (most recent call last):
  File "/Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_items.enaml", line 94, in Main
    func draw(position):
  File "/Users/iridium/anaconda3/envs/enamlx/lib/python3.6/site-packages/enaml/core/compiler_helpers.py", line 736, in add_decl_function
    _override_fail(klass, name)
  File "/Users/iridium/anaconda3/envs/enamlx/lib/python3.6/site-packages/enaml/core/compiler_helpers.py", line 80, in _override_fail
    raise TypeError(msg % (klass.__name__, name))
TypeError: can't override 'GraphicsPathItem.draw'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/iridium/anaconda3/envs/enamlx/bin/enaml-run", line 11, in <module>
    sys.exit(main())
  File "/Users/iridium/anaconda3/envs/enamlx/lib/python3.6/site-packages/enaml/runner.py", line 62, in main
    exec_(code, ns)
  File "/Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_items.enaml", line 16, in 
    from random import randint
  File "/Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_items.enaml", line 18, in Main
    enamldef Main(MainWindow): window:
  File "/Users/iridium/Documents/GitHub/enamlx-master/examples/graphics_view/graphics_items.enaml", line 94, in Main
    func draw(position):
TypeError
(enamlx) iridium-MacBook-Pro:~ iridium$ conda list
# packages in environment at /Users/iridium/anaconda3/envs/enamlx:
#
# Name                    Version                   Build  Channel
atom                      0.4.1            py36h2d50403_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
enaml                     0.10.2           py36h2d50403_1    conda-forge
enamlx                    0.4.0.dev0                <pip>
future                    0.17.0                py36_1000    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libpng                    1.6.35               ha92aebf_2    conda-forge
ncurses                   6.1                  h0a44026_0  
numpy                     1.15.3                    <pip>
openssl                   1.0.2p               h470a237_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
ply                       3.11                       py_1    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
pyqtgraph                 0.10.0                    <pip>
python                    3.6.6                h5001a0f_0    conda-forge
python.app                1.2                    py36_200    conda-forge
qt                        5.6.2                hd4c90f3_9    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
readline                  7.0                  h1de35cc_5  
setuptools                40.5.0                   py36_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
sqlite                    3.25.2               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
wheel                     0.32.2                   py36_0    conda-forge
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               hf3cbc9b_2  
(enamlx) iridium-MacBook-Pro:~ iridium$ 
```

**Comment by Thatfreesky** [comment]
Thanks for your help and your enamlx. It's very useful.
